# this file stores the configuration for the math dataset

dataset_path: "datasets/MedQA_test_200.json"
llm_name: "gemma_base"
log_file_name: "try/medqa_200_single_special_agent_huatuo_7B_4_shot.jsonl"
